const SPECIAL_WEEK = 0;
const SILENCE_SUZUKA = 1;
const TOKAI_TEIO = 2;
const MARUZENSKY = 3;
const OGURI_CAP = 4;
const GOLD_SHIP = 5;
const VODKA = 6;
const DAIWA_SCARLET = 7;
const TAIKI_SHUTTLE = 8;
const GRASS_WONDER = 9;
const MEJIRO_MCQUEEN = 10;
const EL_CONDOR_PASA = 11;
const SYMBOLI_RUDOLF = 12;
const AIR_GROOVE = 13;
const MAYANO_TOP_GUN = 14;
const MEJIRO_RYAN = 15;
const RICE_SHOWER = 16;
const AGNES_TACHYON = 17;
const WINNING_TICKET = 18;
const SAKURA_BAKUSHIN_O = 19;
const SUPER_CREEK = 20;
const HARU_URARA = 21;
const MATIKANE_FUKUKITARU = 22;
const NICE_NATURE = 23;
const KING_HALO = 24;
const CURREN_CHAN = 25;
const TM_OPERA_O = 26;
const BIWA_HAYAHIDE = 27;
const MIHONO_BOURBON = 28;
const NARITA_TAISHIN = 29;

const HORSES = [];

HORSES[SPECIAL_WEEK] = {
  id: SPECIAL_WEEK,
  name: "Special Week",
  mainColor: "purple",
  secondaryColor: "white",
  compatibilities: [NICE_NATURE, GRASS_WONDER, TM_OPERA_O, SUPER_CREEK, MATIKANE_FUKUKITARU, WINNING_TICKET, MEJIRO_MCQUEEN, VODKA, GOLD_SHIP, SYMBOLI_RUDOLF, MAYANO_TOP_GUN, AGNES_TACHYON, EL_CONDOR_PASA, OGURI_CAP, BIWA_HAYAHIDE, KING_HALO, MEJIRO_RYAN, SILENCE_SUZUKA, RICE_SHOWER, TOKAI_TEIO, AIR_GROOVE, MIHONO_BOURBON, DAIWA_SCARLET, NARITA_TAISHIN, MARUZENSKY, CURREN_CHAN, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, HARU_URARA]
};

HORSES[SILENCE_SUZUKA] = {
  id: SILENCE_SUZUKA,
  name: "Silence Suzuka",
  mainColor: "green",
  secondaryColor: "orange",
  compatibilities: [MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, MIHONO_BOURBON, SPECIAL_WEEK, AGNES_TACHYON, SUPER_CREEK, MEJIRO_MCQUEEN, GOLD_SHIP, TM_OPERA_O, NICE_NATURE, WINNING_TICKET, AIR_GROOVE, OGURI_CAP, GRASS_WONDER, TOKAI_TEIO, BIWA_HAYAHIDE, MEJIRO_RYAN, EL_CONDOR_PASA, DAIWA_SCARLET, NARITA_TAISHIN, MARUZENSKY, RICE_SHOWER, VODKA, SYMBOLI_RUDOLF, TAIKI_SHUTTLE, SAKURA_BAKUSHIN_O, KING_HALO, CURREN_CHAN, HARU_URARA]
};

HORSES[TOKAI_TEIO] = {
  id: TOKAI_TEIO,
  name: "Tokai Teio",
  mainColor: "blue",
  secondaryColor: "white",
  compatibilities: [MEJIRO_MCQUEEN, DAIWA_SCARLET, SYMBOLI_RUDOLF, TM_OPERA_O, AIR_GROOVE, BIWA_HAYAHIDE, RICE_SHOWER, VODKA, EL_CONDOR_PASA, SUPER_CREEK, AGNES_TACHYON, NICE_NATURE, GOLD_SHIP, SPECIAL_WEEK, MAYANO_TOP_GUN, MIHONO_BOURBON, WINNING_TICKET, NARITA_TAISHIN, OGURI_CAP, CURREN_CHAN, SILENCE_SUZUKA, GRASS_WONDER, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, MATIKANE_FUKUKITARU, MEJIRO_RYAN, KING_HALO, MARUZENSKY, HARU_URARA]
};

HORSES[MARUZENSKY] = {
  id: MARUZENSKY,
  name: "Maruzensky",
  mainColor: "red",
  secondaryColor: "brown", 
  compatibilities: [MIHONO_BOURBON, TAIKI_SHUTTLE, OGURI_CAP, EL_CONDOR_PASA, GRASS_WONDER, SILENCE_SUZUKA, DAIWA_SCARLET, KING_HALO, SAKURA_BAKUSHIN_O, VODKA, MAYANO_TOP_GUN, CURREN_CHAN, SYMBOLI_RUDOLF, SUPER_CREEK, SPECIAL_WEEK, AGNES_TACHYON, WINNING_TICKET, MATIKANE_FUKUKITARU, RICE_SHOWER, AIR_GROOVE, GOLD_SHIP, TOKAI_TEIO, NARITA_TAISHIN, BIWA_HAYAHIDE, TM_OPERA_O, NICE_NATURE, MEJIRO_MCQUEEN, MEJIRO_RYAN, HARU_URARA]
};

HORSES[OGURI_CAP] = {
  id: OGURI_CAP,
  name: "Oguri Cap",
  mainColor: "white",
  secondaryColor: "yellow",
  compatibilities: [VODKA, GRASS_WONDER, WINNING_TICKET, SUPER_CREEK, NICE_NATURE, SPECIAL_WEEK, MATIKANE_FUKUKITARU, MEJIRO_RYAN, AGNES_TACHYON, DAIWA_SCARLET, MIHONO_BOURBON, EL_CONDOR_PASA, GOLD_SHIP, TM_OPERA_O, MAYANO_TOP_GUN, SYMBOLI_RUDOLF, SILENCE_SUZUKA, TAIKI_SHUTTLE, TOKAI_TEIO, BIWA_HAYAHIDE, MARUZENSKY, MEJIRO_MCQUEEN, KING_HALO, NARITA_TAISHIN, AIR_GROOVE, RICE_SHOWER, CURREN_CHAN, SAKURA_BAKUSHIN_O, HARU_URARA]
};

HORSES[GOLD_SHIP] = {
  id: GOLD_SHIP,
  name: "Gold Ship",
  mainColor: "red",
  secondaryColor: "white",
  compatibilities: [BIWA_HAYAHIDE, MEJIRO_MCQUEEN, MAYANO_TOP_GUN, TM_OPERA_O, SYMBOLI_RUDOLF, SUPER_CREEK, NARITA_TAISHIN, SPECIAL_WEEK, NICE_NATURE, RICE_SHOWER, WINNING_TICKET, OGURI_CAP, TOKAI_TEIO, AIR_GROOVE, SILENCE_SUZUKA, MATIKANE_FUKUKITARU, MEJIRO_RYAN, AGNES_TACHYON, DAIWA_SCARLET, MIHONO_BOURBON, EL_CONDOR_PASA, GRASS_WONDER, VODKA, KING_HALO, HARU_URARA, CURREN_CHAN, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, MARUZENSKY]
};

HORSES[VODKA] = {
  id: VODKA,
  name: "Vodka",
  mainColor: "grey",
  secondaryColor: "yellow",
  compatibilities: [DAIWA_SCARLET, OGURI_CAP, GRASS_WONDER, SPECIAL_WEEK, AGNES_TACHYON, MIHONO_BOURBON, WINNING_TICKET, TOKAI_TEIO, NICE_NATURE, EL_CONDOR_PASA, MATIKANE_FUKUKITARU, MEJIRO_RYAN, MEJIRO_MCQUEEN, AIR_GROOVE, KING_HALO, TM_OPERA_O, SYMBOLI_RUDOLF, SUPER_CREEK, GOLD_SHIP, SILENCE_SUZUKA, TAIKI_SHUTTLE, NARITA_TAISHIN, BIWA_HAYAHIDE, MAYANO_TOP_GUN, MARUZENSKY, RICE_SHOWER, CURREN_CHAN, SAKURA_BAKUSHIN_O, HARU_URARA]
};

HORSES[DAIWA_SCARLET] = {
  id: DAIWA_SCARLET,
  name: "Daiwa Scarlet",
  mainColor: "blue",
  secondaryColor: "red",
  compatibilities: [VODKA, EL_CONDOR_PASA, TOKAI_TEIO, MEJIRO_MCQUEEN, AIR_GROOVE, SUPER_CREEK, OGURI_CAP, SYMBOLI_RUDOLF, TM_OPERA_O, BIWA_HAYAHIDE, GRASS_WONDER, MIHONO_BOURBON, TAIKI_SHUTTLE, RICE_SHOWER, CURREN_CHAN, GOLD_SHIP, AGNES_TACHYON, WINNING_TICKET, SILENCE_SUZUKA, SPECIAL_WEEK, MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, MARUZENSKY, NICE_NATURE, NARITA_TAISHIN, SAKURA_BAKUSHIN_O, MEJIRO_RYAN, KING_HALO, HARU_URARA]
};

HORSES[TAIKI_SHUTTLE] = {
  id: TAIKI_SHUTTLE,
  name: "Taiki Shuttle",
  mainColor: "green",
  secondaryColor: "purple",
  compatibilities: [SAKURA_BAKUSHIN_O, EL_CONDOR_PASA, MARUZENSKY, MIHONO_BOURBON, CURREN_CHAN, DAIWA_SCARLET, RICE_SHOWER, SYMBOLI_RUDOLF, GRASS_WONDER, OGURI_CAP, KING_HALO, TM_OPERA_O, TOKAI_TEIO, VODKA, AIR_GROOVE, SUPER_CREEK, BIWA_HAYAHIDE, MEJIRO_MCQUEEN, MATIKANE_FUKUKITARU, SILENCE_SUZUKA, AGNES_TACHYON, MEJIRO_RYAN, WINNING_TICKET, GOLD_SHIP, SPECIAL_WEEK, NICE_NATURE, MAYANO_TOP_GUN, NARITA_TAISHIN, HARU_URARA]
};

HORSES[GRASS_WONDER] = {
  id: GRASS_WONDER,
  name: "Grass Wonder",
  mainColor: "blue",
  secondaryColor: "brown",
  compatibilities: [EL_CONDOR_PASA, SPECIAL_WEEK, OGURI_CAP, VODKA, MEJIRO_RYAN, NICE_NATURE, AGNES_TACHYON, KING_HALO, DAIWA_SCARLET, MATIKANE_FUKUKITARU, MIHONO_BOURBON, WINNING_TICKET, SYMBOLI_RUDOLF, TAIKI_SHUTTLE, TM_OPERA_O, SILENCE_SUZUKA, MAYANO_TOP_GUN, RICE_SHOWER, GOLD_SHIP, TOKAI_TEIO, MARUZENSKY, AIR_GROOVE, BIWA_HAYAHIDE, MEJIRO_MCQUEEN, SUPER_CREEK, NARITA_TAISHIN, SAKURA_BAKUSHIN_O, CURREN_CHAN, HARU_URARA]
};

HORSES[MEJIRO_MCQUEEN] = {
  id: MEJIRO_MCQUEEN,
  name: "Mejiro McQueen",
  mainColor: "white",
  secondaryColor: "purple",
  compatibilities: [BIWA_HAYAHIDE, SUPER_CREEK, TM_OPERA_O, RICE_SHOWER, GOLD_SHIP, SYMBOLI_RUDOLF, TOKAI_TEIO, DAIWA_SCARLET, MAYANO_TOP_GUN, SPECIAL_WEEK, NICE_NATURE, AIR_GROOVE, EL_CONDOR_PASA, MEJIRO_RYAN, VODKA, SILENCE_SUZUKA, AGNES_TACHYON, WINNING_TICKET, MATIKANE_FUKUKITARU, OGURI_CAP, CURREN_CHAN, SAKURA_BAKUSHIN_O, NARITA_TAISHIN, MIHONO_BOURBON, GRASS_WONDER, TAIKI_SHUTTLE, KING_HALO, MARUZENSKY, HARU_URARA]
};

HORSES[EL_CONDOR_PASA] = {
  id: EL_CONDOR_PASA,
  name: "El Condor Pasa",
  mainColor: "red",
  secondaryColor: "yellow",
  compatibilities: [GRASS_WONDER, DAIWA_SCARLET, SYMBOLI_RUDOLF, TAIKI_SHUTTLE, TM_OPERA_O, RICE_SHOWER, SPECIAL_WEEK, TOKAI_TEIO, VODKA, AIR_GROOVE, OGURI_CAP, SUPER_CREEK, BIWA_HAYAHIDE, MIHONO_BOURBON, MEJIRO_MCQUEEN, GOLD_SHIP, SILENCE_SUZUKA, SAKURA_BAKUSHIN_O, NICE_NATURE, MARUZENSKY, MEJIRO_RYAN, AGNES_TACHYON, WINNING_TICKET, MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, KING_HALO, NARITA_TAISHIN, CURREN_CHAN, HARU_URARA]
};

HORSES[SYMBOLI_RUDOLF] = {
  id: SYMBOLI_RUDOLF,
  name: "Symboli Rudolf",
  mainColor: "green",
  secondaryColor: "brown",
  compatibilities: [RICE_SHOWER, TM_OPERA_O, SUPER_CREEK, BIWA_HAYAHIDE, MEJIRO_MCQUEEN, GOLD_SHIP, TOKAI_TEIO, EL_CONDOR_PASA, SPECIAL_WEEK, MAYANO_TOP_GUN, AIR_GROOVE, DAIWA_SCARLET, NICE_NATURE, TAIKI_SHUTTLE, OGURI_CAP, GRASS_WONDER, AGNES_TACHYON, WINNING_TICKET, VODKA, SAKURA_BAKUSHIN_O, NARITA_TAISHIN, MIHONO_BOURBON, MEJIRO_RYAN, SILENCE_SUZUKA, MATIKANE_FUKUKITARU, CURREN_CHAN, MARUZENSKY, KING_HALO, HARU_URARA]
};

HORSES[AIR_GROOVE] = {
  id: AIR_GROOVE,
  name: "Air Groove",
  mainColor: "blue",
  secondaryColor: "yellow",
  compatibilities: [DAIWA_SCARLET, TOKAI_TEIO, SYMBOLI_RUDOLF, SUPER_CREEK, BIWA_HAYAHIDE, MEJIRO_MCQUEEN, TM_OPERA_O, EL_CONDOR_PASA, RICE_SHOWER, VODKA, WINNING_TICKET, GOLD_SHIP, AGNES_TACHYON, SILENCE_SUZUKA, SPECIAL_WEEK, NARITA_TAISHIN, CURREN_CHAN, SAKURA_BAKUSHIN_O, NICE_NATURE, MATIKANE_FUKUKITARU, MIHONO_BOURBON, MEJIRO_RYAN, OGURI_CAP, GRASS_WONDER, TAIKI_SHUTTLE, MAYANO_TOP_GUN, KING_HALO, MARUZENSKY, HARU_URARA]
};

HORSES[MAYANO_TOP_GUN] = {
  id: MAYANO_TOP_GUN,
  name: "Mayano Top Gun",
  mainColor: "yellow",
  secondaryColor: "brown",
  compatibilities: [GOLD_SHIP, TM_OPERA_O, BIWA_HAYAHIDE, MEJIRO_MCQUEEN, SUPER_CREEK, SILENCE_SUZUKA, SYMBOLI_RUDOLF, SPECIAL_WEEK, NICE_NATURE, RICE_SHOWER, MIHONO_BOURBON, WINNING_TICKET, OGURI_CAP, TOKAI_TEIO, MATIKANE_FUKUKITARU, GRASS_WONDER, AGNES_TACHYON, DAIWA_SCARLET, NARITA_TAISHIN, MEJIRO_RYAN, VODKA, AIR_GROOVE, EL_CONDOR_PASA, MARUZENSKY, KING_HALO, CURREN_CHAN, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, HARU_URARA]
};

HORSES[MEJIRO_RYAN] = {
  id: MEJIRO_RYAN,
  name: "Mejiro Ryan",
  mainColor: "cyan",
  secondaryColor: "brown",
  compatibilities: [WINNING_TICKET, OGURI_CAP, GRASS_WONDER, NICE_NATURE, AGNES_TACHYON, SPECIAL_WEEK, MATIKANE_FUKUKITARU, VODKA, MEJIRO_MCQUEEN, GOLD_SHIP, RICE_SHOWER, SILENCE_SUZUKA, NARITA_TAISHIN, BIWA_HAYAHIDE, AIR_GROOVE, EL_CONDOR_PASA, SYMBOLI_RUDOLF, TOKAI_TEIO, MAYANO_TOP_GUN, KING_HALO, SUPER_CREEK, TM_OPERA_O, MIHONO_BOURBON, SAKURA_BAKUSHIN_O, DAIWA_SCARLET, TAIKI_SHUTTLE, MARUZENSKY, CURREN_CHAN, HARU_URARA]
};

HORSES[RICE_SHOWER] = {
  id: RICE_SHOWER,
  name: "Rice Shower",
  mainColor: "blue",
  secondaryColor: "magenta",
  compatibilities: [SYMBOLI_RUDOLF, MEJIRO_MCQUEEN, SUPER_CREEK, TM_OPERA_O, BIWA_HAYAHIDE, EL_CONDOR_PASA, GOLD_SHIP, TOKAI_TEIO, MAYANO_TOP_GUN, NICE_NATURE, SPECIAL_WEEK, AIR_GROOVE, DAIWA_SCARLET, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, MATIKANE_FUKUKITARU, MEJIRO_RYAN, AGNES_TACHYON, GRASS_WONDER, MIHONO_BOURBON, SILENCE_SUZUKA, WINNING_TICKET, OGURI_CAP, VODKA, CURREN_CHAN, NARITA_TAISHIN, MARUZENSKY, KING_HALO, HARU_URARA]
};

HORSES[AGNES_TACHYON] = {
  id: AGNES_TACHYON,
  name: "Agnes Tachyon",
  mainColor: "white",
  secondaryColor: "brown",
  compatibilities: [MATIKANE_FUKUKITARU, NICE_NATURE, VODKA, SPECIAL_WEEK, WINNING_TICKET, OGURI_CAP, MEJIRO_RYAN, GRASS_WONDER, TOKAI_TEIO, MIHONO_BOURBON, SILENCE_SUZUKA, KING_HALO, TM_OPERA_O, MEJIRO_MCQUEEN, AIR_GROOVE, GOLD_SHIP, SYMBOLI_RUDOLF, SUPER_CREEK, NARITA_TAISHIN, RICE_SHOWER, DAIWA_SCARLET, BIWA_HAYAHIDE, MAYANO_TOP_GUN, EL_CONDOR_PASA, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, CURREN_CHAN, MARUZENSKY, HARU_URARA]
};

HORSES[WINNING_TICKET] = {
  id: WINNING_TICKET,
  name: "Winning Ticket",
  mainColor: "red",
  secondaryColor: "green",
  compatibilities: [SPECIAL_WEEK, OGURI_CAP, BIWA_HAYAHIDE, NICE_NATURE, NARITA_TAISHIN, MATIKANE_FUKUKITARU, MEJIRO_RYAN, AGNES_TACHYON, VODKA, GRASS_WONDER, GOLD_SHIP, MAYANO_TOP_GUN, AIR_GROOVE, SUPER_CREEK, TOKAI_TEIO, MEJIRO_MCQUEEN, SILENCE_SUZUKA, SYMBOLI_RUDOLF, TM_OPERA_O, MIHONO_BOURBON, KING_HALO, DAIWA_SCARLET, EL_CONDOR_PASA, RICE_SHOWER, SAKURA_BAKUSHIN_O, MARUZENSKY, CURREN_CHAN, TAIKI_SHUTTLE, HARU_URARA]
};

HORSES[SAKURA_BAKUSHIN_O] = {
  id: SAKURA_BAKUSHIN_O,
  name: "Sakura Bakushin O",
  mainColor: "pink",
  secondaryColor: "white",
  compatibilities: [TAIKI_SHUTTLE, CURREN_CHAN, RICE_SHOWER, MIHONO_BOURBON, MEJIRO_MCQUEEN, AIR_GROOVE, EL_CONDOR_PASA, SYMBOLI_RUDOLF, SUPER_CREEK, TOKAI_TEIO, KING_HALO, TM_OPERA_O, BIWA_HAYAHIDE, MARUZENSKY, DAIWA_SCARLET, MEJIRO_RYAN, SILENCE_SUZUKA, MATIKANE_FUKUKITARU, NICE_NATURE, AGNES_TACHYON, WINNING_TICKET, GRASS_WONDER, HARU_URARA, OGURI_CAP, GOLD_SHIP, SPECIAL_WEEK, MAYANO_TOP_GUN, VODKA, NARITA_TAISHIN]
};

HORSES[SUPER_CREEK] = {
  id: SUPER_CREEK,
  name: "Super Creek",
  mainColor: "white",
  secondaryColor: "blue",
  compatibilities: [BIWA_HAYAHIDE, MEJIRO_MCQUEEN, SYMBOLI_RUDOLF, TM_OPERA_O, RICE_SHOWER, SPECIAL_WEEK, GOLD_SHIP, MAYANO_TOP_GUN, OGURI_CAP, AIR_GROOVE, DAIWA_SCARLET, NICE_NATURE, TOKAI_TEIO, EL_CONDOR_PASA, MATIKANE_FUKUKITARU, SILENCE_SUZUKA, NARITA_TAISHIN, WINNING_TICKET, AGNES_TACHYON, VODKA, SAKURA_BAKUSHIN_O, MIHONO_BOURBON, CURREN_CHAN, TAIKI_SHUTTLE, MEJIRO_RYAN, GRASS_WONDER, MARUZENSKY, KING_HALO, HARU_URARA]
};

HORSES[HARU_URARA] = {
  id: HARU_URARA,
  name: "Haru Urara", 
  mainColor: "white",
  secondaryColor: "red",
  compatibilities: [KING_HALO, GOLD_SHIP, CURREN_CHAN, SAKURA_BAKUSHIN_O, NARITA_TAISHIN, MIHONO_BOURBON, SPECIAL_WEEK, TAIKI_SHUTTLE, MARUZENSKY, TM_OPERA_O, NICE_NATURE, DAIWA_SCARLET, MEJIRO_MCQUEEN, AGNES_TACHYON, WINNING_TICKET, VODKA, AIR_GROOVE, OGURI_CAP, GRASS_WONDER, SILENCE_SUZUKA, SUPER_CREEK, TOKAI_TEIO, MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, EL_CONDOR_PASA, BIWA_HAYAHIDE, RICE_SHOWER, SYMBOLI_RUDOLF, MEJIRO_RYAN]
};

HORSES[MATIKANE_FUKUKITARU] = {
  id: MATIKANE_FUKUKITARU,
  name: "Matikane Fukukitaru",
  mainColor: "blue",
  secondaryColor: "orange",
  compatibilities: [SPECIAL_WEEK, AGNES_TACHYON, SILENCE_SUZUKA, WINNING_TICKET, OGURI_CAP, NICE_NATURE, VODKA, GRASS_WONDER, MEJIRO_RYAN, SUPER_CREEK, GOLD_SHIP, MAYANO_TOP_GUN, MIHONO_BOURBON, MEJIRO_MCQUEEN, RICE_SHOWER, KING_HALO, BIWA_HAYAHIDE, AIR_GROOVE, DAIWA_SCARLET, TM_OPERA_O, TOKAI_TEIO, NARITA_TAISHIN, EL_CONDOR_PASA, SYMBOLI_RUDOLF, TAIKI_SHUTTLE, SAKURA_BAKUSHIN_O, MARUZENSKY, CURREN_CHAN, HARU_URARA]
};

HORSES[NICE_NATURE] = {
  id: NICE_NATURE,
  name: "Nice Nature",
  mainColor: "red",
  secondaryColor: "green",
  compatibilities: [SPECIAL_WEEK, MEJIRO_MCQUEEN, AGNES_TACHYON, OGURI_CAP, GOLD_SHIP, TM_OPERA_O, WINNING_TICKET, SUPER_CREEK, MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, MEJIRO_RYAN, VODKA, GRASS_WONDER, BIWA_HAYAHIDE, RICE_SHOWER, SYMBOLI_RUDOLF, TOKAI_TEIO, KING_HALO, SILENCE_SUZUKA, NARITA_TAISHIN, MIHONO_BOURBON, AIR_GROOVE, EL_CONDOR_PASA, DAIWA_SCARLET, SAKURA_BAKUSHIN_O, CURREN_CHAN, TAIKI_SHUTTLE, MARUZENSKY, HARU_URARA]
};

HORSES[KING_HALO] = {
  id: KING_HALO,
  name: "King Halo",
  mainColor: "green",
  secondaryColor: "blue",
  compatibilities: [SPECIAL_WEEK, GRASS_WONDER, NICE_NATURE, AGNES_TACHYON, VODKA, MATIKANE_FUKUKITARU, MIHONO_BOURBON, WINNING_TICKET, OGURI_CAP, CURREN_CHAN, TAIKI_SHUTTLE, SAKURA_BAKUSHIN_O, MARUZENSKY, MEJIRO_RYAN, EL_CONDOR_PASA, MEJIRO_MCQUEEN, TOKAI_TEIO, HARU_URARA, AIR_GROOVE, TM_OPERA_O, GOLD_SHIP, SILENCE_SUZUKA, DAIWA_SCARLET, NARITA_TAISHIN, SYMBOLI_RUDOLF, SUPER_CREEK, BIWA_HAYAHIDE, MAYANO_TOP_GUN, RICE_SHOWER]
};

HORSES[CURREN_CHAN] = {
  id: CURREN_CHAN,
  name: "Curren Chan",
  mainColor: "black",
  secondaryColor: "red",
  compatibilities: [SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, DAIWA_SCARLET, TOKAI_TEIO, MEJIRO_MCQUEEN, AIR_GROOVE, KING_HALO, SUPER_CREEK, TM_OPERA_O, BIWA_HAYAHIDE, MIHONO_BOURBON, RICE_SHOWER, EL_CONDOR_PASA, SYMBOLI_RUDOLF, MARUZENSKY, VODKA, AGNES_TACHYON, OGURI_CAP, SILENCE_SUZUKA, SPECIAL_WEEK, NARITA_TAISHIN, HARU_URARA, WINNING_TICKET, GOLD_SHIP, NICE_NATURE, MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, GRASS_WONDER, MEJIRO_RYAN]
};

HORSES[TM_OPERA_O] = {
  id: TM_OPERA_O,
  name: "TM Opera O",
  mainColor: "pink",
  secondaryColor: "yellow",
  compatibilities: [BIWA_HAYAHIDE, SYMBOLI_RUDOLF, SUPER_CREEK, MEJIRO_MCQUEEN, RICE_SHOWER, SPECIAL_WEEK, GOLD_SHIP, MAYANO_TOP_GUN, TOKAI_TEIO, EL_CONDOR_PASA, NICE_NATURE, AIR_GROOVE, DAIWA_SCARLET, OGURI_CAP, AGNES_TACHYON, GRASS_WONDER, SILENCE_SUZUKA, NARITA_TAISHIN, WINNING_TICKET, VODKA, MIHONO_BOURBON, TAIKI_SHUTTLE, MATIKANE_FUKUKITARU, CURREN_CHAN, SAKURA_BAKUSHIN_O, MEJIRO_RYAN, KING_HALO, MARUZENSKY, HARU_URARA]
};

HORSES[BIWA_HAYAHIDE] = {
  id: BIWA_HAYAHIDE,
  name: "Biwa Hayahide",
  mainColor: "black",
  secondaryColor: "purple",
  compatibilities: [TM_OPERA_O, MEJIRO_MCQUEEN, SUPER_CREEK, SYMBOLI_RUDOLF, RICE_SHOWER, GOLD_SHIP, MAYANO_TOP_GUN, WINNING_TICKET, AIR_GROOVE, SPECIAL_WEEK, TOKAI_TEIO, NARITA_TAISHIN, DAIWA_SCARLET, NICE_NATURE, EL_CONDOR_PASA, OGURI_CAP, SILENCE_SUZUKA, MATIKANE_FUKUKITARU, MEJIRO_RYAN, AGNES_TACHYON, MIHONO_BOURBON, VODKA, CURREN_CHAN, GRASS_WONDER, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE, KING_HALO, MARUZENSKY, HARU_URARA]
};

HORSES[MIHONO_BOURBON] = {
  id: MIHONO_BOURBON,
  name: "Mihono Bourbon",
  mainColor: "white",
  secondaryColor: "pink",
  compatibilities: [MARUZENSKY, SILENCE_SUZUKA, VODKA, OGURI_CAP, TAIKI_SHUTTLE, MAYANO_TOP_GUN, GRASS_WONDER, DAIWA_SCARLET, EL_CONDOR_PASA, AGNES_TACHYON, TOKAI_TEIO, SAKURA_BAKUSHIN_O, MATIKANE_FUKUKITARU, WINNING_TICKET, KING_HALO, GOLD_SHIP, SPECIAL_WEEK, TM_OPERA_O, NICE_NATURE, NARITA_TAISHIN, MEJIRO_MCQUEEN, RICE_SHOWER, AIR_GROOVE, SYMBOLI_RUDOLF, SUPER_CREEK, BIWA_HAYAHIDE, CURREN_CHAN, MEJIRO_RYAN, HARU_URARA]
};

HORSES[NARITA_TAISHIN] = {
  id: NARITA_TAISHIN,
  name: "Narita Taishin",
  mainColor: "pink",
  secondaryColor: "brown",
  compatibilities: [GOLD_SHIP, WINNING_TICKET, BIWA_HAYAHIDE, SUPER_CREEK, TM_OPERA_O, TOKAI_TEIO, AGNES_TACHYON, AIR_GROOVE, NICE_NATURE, MIHONO_BOURBON, MEJIRO_MCQUEEN, MEJIRO_RYAN, OGURI_CAP, SILENCE_SUZUKA, SYMBOLI_RUDOLF, SPECIAL_WEEK, MATIKANE_FUKUKITARU, MAYANO_TOP_GUN, VODKA, DAIWA_SCARLET, EL_CONDOR_PASA, GRASS_WONDER, RICE_SHOWER, KING_HALO, CURREN_CHAN, HARU_URARA, MARUZENSKY, SAKURA_BAKUSHIN_O, TAIKI_SHUTTLE]
}

export { HORSES };